# -*- coding: utf-8 -*-
"""Linear Search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KlaY7JdajOJZsVDsGclV4leuJnk46Mrk

**Linear Search Basic Implementation in Functions**
"""

def linear_search(arr, target):
    for index, value in enumerate(arr):
        if value == target:
            return index  # Found
    return -1  # Not found

# Example
data = [10, 25, 37, 42, 53]
print(linear_search(data, 42))  # Output: 3

"""**Linear Search Implementation in OOP**"""

class LinearSearch:
    """Simple Linear Search class implementation."""

    def __init__(self, data=None):
        self.data = data if data is not None else []

    def search(self, target):
        """Search for target and return index, or -1 if not found."""
        for index, value in enumerate(self.data):
            if value == target:
                return index
        return -1

    def contains(self, target):
        """Check if target exists in data."""
        return self.search(target) != -1

    def add(self, item):
        """Add item to data."""
        self.data.append(item)

    def __str__(self):
        return f"LinearSearch(data={self.data})"


# Example usage
if __name__ == "__main__":
    # Create searcher with data
    searcher = LinearSearch([10, 25, 37, 42, 53])

    # Search examples
    print(searcher.search(42))    # Output: 3
    print(searcher.search(99))    # Output: -1
    print(searcher.contains(25))  # Output: True

    # Add new element and search
    searcher.add(99)
    print(searcher.search(99))    # Output: 5

    print(searcher)  # Display current state